export const  GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const  GET_ALL_CATEGORIES_SUCCESS= "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL";

export const POST_CATEGORIES= "POST_CATEGORIES";
export const  POST_CATEGORIES_SUCCESS= "POST_CATEGORIES_SUCCESS";
export const POST_CATEGORIES_FAIL= "POST_CATEGORIES_FAIL";

export const PUT_CATEGORIES= "PUT_CATEGORIES";
export const  PUT_CATEGORIES_SUCCESS= "PUT_CATEGORIES_SUCCESS";
export const PUT_CATEGORIES_FAIL= "PUT_CATEGORIES_FAIL";

export const DELETE_CATEGORIES= "DELETE_CATEGORIES";
export const  DELETE_CATEGORIES_SUCCESS= "DELETE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORIES_FAIL= "DELETE_CATEGORIES_FAIL";

export const  GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const  GET_ALL_PRODUCT_SUCCESS= "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const POST_PRODUCT= "POST_PRODUCT";
export const  POST_PRODUCT_SUCCESS= "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_FAIL= "POST_PRODUCT_FAIL";

export const PUT_PRODUCT= "PUT_PRODUCT";
export const  PUT_PRODUCT_SUCCESS= "PUT_PRODUCT_SUCCESS";
export const PUT_PRODUCT_FAIL= "PUT_PRODUCT_FAIL";

export const DELETE_PRODUCT= "DELETE_PRODUCT";
export const  DELETE_PRODUCT_SUCCESS= "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL= "DELETE_PRODUCT_FAIL";

export const COMPLETE = "COMPLETE";
export const EMPTY_POST ="EMPTY_POST";
export const EMPTY_PUT ="EMPTY_PUT";

export const COMPLETE_PRODUCT = "COMPLETE_PRODUCT";
export const EMPTY_POST_PRODUCT ="EMPTY_POST_PRODUCT";
export const EMPTY_PUT_PRODUCT ="EMPTY_PUT_PRODUCT";